import { Category, TagKey } from '@prisma/client';

// [시나리오이름, 규칙, 기대_베이스개수, 기대_프로틴개수, 기대_토핑개수, 기대_지방개수, 기대_드레싱개수, 총개수
export const assembleSaladRuleCases: [
  TagKey,
  Record<Category, number>,
  number,
  number,
  number,
  number,
  number,
  number,
][] = [
  [
    TagKey.overall_health,
    {
      [Category.BASE]: 1,
      [Category.PROTEIN]: 1,
      [Category.TOPPING]: 2,
      [Category.FAT]: 1,
      [Category.DRESSING]: 1,
    },
    1,
    1,
    2,
    1,
    1,
    6,
  ],
  [
    TagKey.weight_loss,
    {
      [Category.BASE]: 2,
      [Category.PROTEIN]: 1,
      [Category.TOPPING]: 1,
      [Category.FAT]: 1,
      [Category.DRESSING]: 1,
    },
    2,
    1,
    1,
    1,
    1,
    6,
  ],
  [
    TagKey.muscle_gain,
    {
      [Category.BASE]: 1,
      [Category.PROTEIN]: 2,
      [Category.TOPPING]: 2,
      [Category.FAT]: 1,
      [Category.DRESSING]: 1,
    },
    1,
    2,
    2,
    1,
    1,
    7,
  ],
  [
    TagKey.light_meal,
    {
      [Category.BASE]: 1,
      [Category.PROTEIN]: 1,
      [Category.TOPPING]: 1,
      [Category.FAT]: 1,
      [Category.DRESSING]: 1,
    },
    1,
    1,
    1,
    1,
    1,
    5,
  ],
];

export const mockIngredients = [
  { id: 24, name: '옥수수', category: Category.TOPPING, tags: [] },
  {
    id: 19,
    name: '오이',
    category: Category.TOPPING,
    tags: [],
  },
  {
    id: 29,
    name: '오리엔탈 드레싱',
    category: Category.DRESSING,
    tags: [],
  },
  {
    id: 4,
    name: '양상추',
    category: Category.BASE,
    tags: [],
  },
  {
    id: 34,
    name: '치아씨드',
    category: Category.FAT,
    tags: [],
  },
  {
    id: 30,
    name: '발사믹 비네그레트',
    category: Category.DRESSING,
    tags: [],
  },
  {
    id: 37,
    name: '페타 치즈',
    category: Category.FAT,
    tags: [],
  },
  {
    id: 20,
    name: '파프리카',
    category: Category.TOPPING,
    tags: [],
  },
  {
    id: 32,
    name: '요거트 드레싱',
    category: Category.DRESSING,
    tags: [],
  },
  {
    id: 33,
    name: '올리브 오일 (엑스트라 버진)',
    category: Category.FAT,
    tags: [],
  },
  {
    id: 13,
    name: '리코타 치즈',
    category: Category.PROTEIN,
    tags: [],
  },
  {
    id: 1,
    name: '로메인 상추',
    category: Category.BASE,
    tags: [],
  },
  {
    id: 5,
    name: '믹스 채소',
    category: Category.BASE,
    tags: [],
  },
  {
    id: 18,
    name: '방울토마토',
    category: Category.TOPPING,
    tags: [],
  },
  {
    id: 27,
    name: '당근',
    category: Category.TOPPING,
    tags: [],
  },
  {
    id: 9,
    name: '연어',
    category: Category.PROTEIN,
    tags: [],
  },
];
