name: CI Checks

on:
  push:
    branches: [stage]
  pull_request:
    branches: [main]

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test --ci --coverage # --ci: 비-watch 모드, --coverage: 커버리지 리포트 생성

      - name: Run build
        run: pnpm build
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          DIRECT_URL: ${{secrets.DIRECT_URL}}
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
          NEXT_PUBLIC_SUPABASE_STORAGE_URL: ${{secrets.NEXT_PUBLIC_SUPABASE_STORAGE_URL}}
          NEXT_PUBLIC_SUPABASE_URL: ${{secrets.NEXT_PUBLIC_SUPABASE_URL}}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY}}
          NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY: ${{secrets.NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY}}
